# Normal
# empaquetar: mvnw clean package
FROM openjdk:17-alpine
COPY target/contactos-0.0.1-SNAPSHOT.jar /usr/app.jar
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app.jar"]

# Nativa
# generar: mvnw clean spring-boot:build-image
# FROM contactos:0.0.1-SNAPSHOT
# ENV PORT=8080
# EXPOSE 8080

# crear imagen: docker build -t ms-contactos .
# crear contenedor: docker run -d --name ms-contactos -p 8020:8080 --env DB_SERVER=mongodb:27017 --env DISCOVERY_URL=http://ms-eureka-server:8761 --env CONFIGSRV_URL=http://ms-config-server:8888/ --env ADMINSRV_URL=http://host.docker.internal:8081 --env ZIPKINSRV_URL=http://zipkin:9411 --network microservicios ms-contactos
# añadir a red: docker network connect microservicios ms-contactos
