# Normal
# empaquetar: mvnw clean package
FROM openjdk:17-alpine
COPY target/ms.apigateway.server-1.0.0.jar /usr/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app.jar"]

# Nativa
# generar: mvnw clean spring-boot:build-image
# FROM ms.apigateway.server:1.0.0
# EXPOSE 8080

# crear imagen: docker build -t ms-apigateway-server .
# crear contenedor: docker run -d --name ms-apigateway-server -p 8080:8080 --env DISCOVERY_URL=http://ms-eureka-server:8761 --env FRONTEND_URL=http://angular-server:4200/ --network microservicios ms-apigateway-server
# crear contenedor: docker run -d --name ms-apigateway-server -p 8080:8080 --env DISCOVERY_URL=http://ms-eureka-server:8761 --env FRONTEND_URL=http://host.docker.internal:4200/ --network microservicios ms-apigateway-server
# añadir a red: docker network connect microservicios ms-apigateway-server
