# Normal
# empaquetar: mvnw clean package
#FROM openjdk:17-alpine
#COPY target/megusta-0.0.1-SNAPSHOT.jar /usr/app.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","/usr/app.jar"]

# Nativa
# generar: mvnw clean spring-boot:build-image
FROM megusta:0.0.1-SNAPSHOT
EXPOSE 8080

# crear imagen: docker build -t ms-megusta .
# crear contenedor: docker run -d --name ms-megusta -p 8030:8080 --env REDIS_HOST=redis --env DISCOVERY_URL=http://ms-eureka-server:8761 --env CONFIGSRV_URL=http://ms-config-server:8888/ --env ADMINSRV_URL=http://host.docker.internal:8081 --env ZIPKINSRV_URL=http://zipkin:9411 --network microservicios ms-megusta
# añadir a red: docker network connect microservicios ms-megusta
