# Normal
# empaquetar: mvnw clean package
FROM openjdk:17-alpine
COPY target/ms.eureka.server-1.0.0.jar /usr/app.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/usr/app.jar"]

# Nativa
# generar: mvnw clean spring-boot:build-image
#FROM ms.eureka.server:1.0.0
#EXPOSE 8761

# crear imagen: docker build -t ms-eureka-server .
# crear contenedor: docker run -d --name ms-eureka-server -p 8761:8761 ms-eureka-server
# añadir a red: docker network connect microservicios ms-eureka-server