# Nativa
# generar: mvnw clean spring-boot:build-image
FROM ms.eureka.server:1.0.0
EXPOSE 8761

# crear imagen: docker build -f dockerfile-native -t ms-eureka-server-native .
# crear contenedor: docker run -d --name ms-eureka-server-native -p 8761:8761 ms-eureka-server-native
# añadir a red: docker network connect microservicios ms-eureka-server-native